### ISSUE TITLE
Setup instructions are not Windows or MacOS frendly

### ISSUE THREAD

**Issue by MrBartusek** [MoritzHayden/bosco#49]
Hey! Current [setup guide](https://github.com/MoritzHayden/bosco#local-development) assumes that developer uses Linux-based system which is [usually not the case](https://survey.stackoverflow.co/2023/#section-most-popular-technologies-operating-system). While it is not a technical limitation merely seems to me it's only a desire to use shell scripts for some reason.

For example setup script can just be a set of commands:

```sh
pip install pipenv
cd src # this can even be removed if Pipfile is not in src, because why would it even not be in root?
pipenv install --dev
```

And run script can just be:
```
pipenv run python src/bot.py
```

These shell scripts are nice simplification but only for Linux users

**Comment by MoritzHayden** [comment]
You're correct, the scripts will work for anyone using bash (e.g. Linux and MacOS). However, they can also be executed on Windows directly using WSL, for example, without the need for a VM (in fact, I wrote the scripts on Windows!)

I think having these scripts/commands makes troubleshooting and distribution easier, since we're all running the exact same code to install/test/run the project. The exact commands could also be added to the `README`, but since those commands can already be found in each individual script and the information would be duplicated, I think it would be better to leave it as-is
