### ISSUE TITLE
Automated deep dive report

### ISSUE THREAD

**Issue by chrislem1** [MoritzHayden/bosco#71]
Would it be possible for bosco to automatically announce the deep dives as they drop? That would be cool.

**Comment by MoritzHayden** [comment]
Do you mean sending automatically sending the deep dive embed to a certain channel in the servers which Bosco has been added to?

**Comment by chrislem1** [comment]
Yeah

**Comment by MoritzHayden** [comment]
I agree that this would be a really nice feature and, in theory, it's definitely possible!

It would require some configuration on a server-by-server basis. At the very least, a server administrator would have to configure which channel to send the deep dives to. In order for that to happen, the configuration settings would need to be stored in a database for Bosco to access.

Right now, Bosco is completely stateless. It fetches deep dive information from [DRG API](https://drgapi.com/), formats it, and returns it. A database has not been required to maintain the current features, so I have not created one. Since I'm funding Bosco 100% personally, and this feature would require the creation of additional cloud resources, I'd rather not incur the additional expenses required to add this feature right now (although, it is certainly a possibility for the future). Thanks for sending your idea!
